default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: vigneshg
  password: vigneshg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  database: backend_production
  username: backend
  password: <%= ENV["DATABASE_URL"] %>
