default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development
  username: vigneshg
  password: vigneshg
  host: localhost

test:
  <<: *default
  database: backend_test
  username: vigneshg
  password: vigneshg
  host: localhost

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
